services:
  api:
    build: ./api
    volumes:
      - ./api/main.py:/app/main.py

  frontend:
    build:
      context: ../
      dockerfile: ./sherlock-web/frontend/Dockerfile
    command: npm run dev
    volumes:
      - ./frontend/app:/app/app/
      - ./frontend/public:/app/public
    ports:
      - 3000:3000
    depends_on:
      - api
